# Generated by Django 2.2 on 2019-04-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='notset', max_length=200, unique=True)),
                ('fanNumber', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FanCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='fanCount', max_length=200)),
                ('fanCount', models.IntegerField(default=0)),
            ],
        ),
    ]
