# Generated by Django 2.2 on 2019-04-28 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FanCounter',
        ),
    ]
