# Generated by Django 2.2 on 2019-04-29 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_delete_fancounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='FanCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='fanCount', max_length=200)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
