# Generated by Django 2.2 on 2019-05-28 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_fancounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256)),
                ('genre', models.CharField(default='', max_length=256)),
                ('location', models.CharField(default='', max_length=256)),
                ('socialLink', models.CharField(default='', max_length=256)),
                ('favoriteTrack', models.CharField(default='', max_length=256)),
                ('description', models.CharField(default='', max_length=256)),
                ('imageLink', models.CharField(default='', max_length=256)),
            ],
        ),
    ]
