# Generated by Django 2.2 on 2019-06-20 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_blog_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(default='', max_length=256, unique=True)),
                ('title', models.CharField(default='', max_length=256, unique=True)),
                ('description', models.CharField(default='', max_length=3000)),
            ],
        ),
    ]
