# Generated by Django 2.2 on 2019-06-20 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_tab_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tab',
            name='videoLink',
            field=models.CharField(default='', max_length=256, unique=True),
        ),
    ]
