# Generated by Django 2.2 on 2020-01-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_tab_videolink'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='notset', max_length=200, unique=True)),
                ('link', models.CharField(default='notset', max_length=200)),
            ],
        ),
    ]
